"""Backend contract implemented by IVI-COM and the deterministic simulator."""

from __future__ import annotations

from typing import Protocol

from ..types import (
    Capabilities,
    Identity,
    InstrumentStatus,
    Measurement,
    OperatingState,
    SafetyLimits,
    Setpoints,
)


class NHRBackend(Protocol):
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def read_identity(self) -> Identity: ...
    def read_capabilities(self) -> Capabilities: ...
    def read_status(self) -> InstrumentStatus: ...
    def read_measurement(self) -> Measurement: ...
    def configure_safety_limits(self, limits: SafetyLimits) -> None: ...
    def configure_setpoints(self, setpoints: Setpoints) -> None: ...
    def set_enabled(self, enabled: bool) -> None: ...
    def set_state(self, state: OperatingState) -> None: ...
    def set_watchdog(self, enabled: bool) -> None: ...
